services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dawsheet
      POSTGRES_USER: dawsheet
      POSTGRES_PASSWORD: dawsheet
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://dawsheet:dawsheet@db:5432/dawsheet
      CORS_ORIGINS: "http://localhost:3001"
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  db_data:
